#! /usr/bin/env -S -i /bin/bash

# A configuration wrapper around restic

[ "x$(stat -c '%u:%a' "$(realpath "$0")")" != "x0:755" ] && echo "error: insecure $(basename $0)" 1>&2 && exit 1

CONFIGS+=( $(find /etc/resticw/* $HOME/.config/resticw/* -type d 2>/dev/null | awk -F '/' '{print $NF}' | sort -u) )
config_list="all|$(IFS='|' ; echo -e "${CONFIGS[*]}")"
[ ${#CONFIGS[@]} == 0 ] && config_list="none"
[ $# -lt 2 ] && echo "usage: $(basename $0) <$config_list> <cmd> [args]" 1>&2 && exit 1

# print a sheet with the backup keys to the local printer
if [[ "x$2" == "xkeys-to-lpr" ]]; then
    texttopdf=/usr/libexec/cups/filter/texttopdf
    $0 $1 keys $@ | $texttopdf 1 1 1 1 'cpi=18 lpi=10 portrait' 2>/dev/null | lpr
    exit 0
fi

# As the 'backup' user:
# - the config must be owned by root
uid=$UID
[ "x$UID" == "x$(id -u backup)" ] && uid=0

TARGET="${1//[^a-zA-Z0-9-]/}" # only accept alphanumerics
[ "$TARGET" != "$1" ] && echo "error: $1: invalid target" 1>&2 && exit 1
shift
if [ "x$TARGET" == "xall" ]; then
    [[ ! "$@" =~ (--quiet) ]] && [ "x$1" != "xkeys" ] && set -x
    for i in ${CONFIGS[@]}; do
        "$0" "$i" $@
    done
    exit 0
fi

# $HOME/.config/resticw superceeds /etc/resticw config
DIR=""
for i in "/etc/resticw/$TARGET" "$HOME/.config/resticw/$TARGET"; do
    [ -d "$i" ] && DIR="$i"
done
[ ! -d "$DIR" ] && echo "error: $TARGET: not a valid config dir" 1>&2 && exit 1
[ "x$(stat -c '%u:%a' "$DIR")" != "x$uid:755" ] && echo "error: '$DIR' permissions must be 755 and owned by $(id -un $uid) ($uid)" 1>&2 && exit 1
# required config files
for i in passwd repo; do
    [ ! -f "$DIR/$i" ] && echo "error: $DIR/$i: missing" 1>&2 && exit 1
done
# check ownership and permissions
for f in passwd repo backup exclude hook retention env mount mirror; do
    [ ! -f "$DIR/$f" ] && continue
    ff="$(realpath "$DIR/$f")"
    [ "x$(stat -c '%u' "$ff")" != "x$uid" ] && echo "error: $DIR/$f not owned by $(id -un $uid) ($uid)" 1>&2 && exit 1
    case "$f" in
        passwd) mod="600";;
        env) mod="700";;
        hook) mod="750";;
        *) mod="644" ;;
    esac
    [ "x$(stat -c '%a' "$ff")" != "x$mod" ] && echo "error: $DIR/$f permissions must be $mod" 1>&2 && exit 1
    [ $f == "hook" ] && [ ! -x "$DIR/hook" ] && echo "error: $DIR/$f not executable by user '$USER' ($UID)" 1>&2 && exit 1
done

# As the 'backup' user:
# - the cache dir is /var/cache/restic
# (The default RESTIC_CACHE_DIR is $XDG_CACHE_HOME/restic,
#  or ~/.cache/restic if XDG_CACHE_HOME is not set.)
[ "x$uid" == "x0" ] && export RESTIC_CACHE_DIR=/var/cache/restic
if [ "x$UID" == "x0" ]; then
    mkdir -p -m 750 "$RESTIC_CACHE_DIR"
    chown backup:backup "$RESTIC_CACHE_DIR"

    mnt="$(cat $DIR/mount 2>/dev/null)"
    trap 'umount "$mnt" 2>/dev/null' EXIT
    for uuid in $(grep "$mnt" /etc/fstab | cut -d' ' -f1 | sed 's/UUID=//'); do
        [ ! -f "/dev/disk/by-uuid/$uuid" ] && continue
        mount -o noexec "UUID=$uuid" "$mnt" 2>/dev/null
    done
    [ ! -d "$mnt/" ] && echo "error: failed to mount $mnt" 1>&2 && exit 1

    set -e
    PRIV=-all,+dac_read_search  # the 'backup' user needs 'root' read-only access
    setpriv --reuid backup --regid backup --clear-groups --reset-env \
        --bounding-set=${PRIV} --inh-caps=${PRIV} --ambient-caps=${PRIV} \
        --no-new-privs \
        -- $0 "$TARGET" "$@"
    exit $?
fi
# check permissions are "safe"
#id && setpriv --dump

rotate=()
if [ -f "$DIR/retention" ]; then
    for i in hourly daily weekly monthly yearly; do
        x="$(grep -1E "^ *$i: *[0-9][0-9]*[^hdmy] *\$" $DIR/retention)"
        [ -n "$x" ] && echo "error: $DIR/retention: unrecognized retention period" 1>&2 && exit 1
        n="$(grep -E "^ *$i: *[0-9][0-9]*[hdmy] *\$" $DIR/retention | sed -e 's/.*: *//' -e 's/ *$//')"
        rotate+=("--keep-within-$i $n")
    done
fi

CMD="${1//[^a-zA-Z0-9-]/}" # only accept alphanumerics
shift

NCDU=/usr/bin/ncdu
REDU=/usr/bin/redu
RCLONE=/usr/bin/rclone
RESTIC=/usr/bin/restic
passwd="--password-file=$DIR/passwd"
repo="--repository-file=$DIR/repo"
case "$CMD" in
    backup)
        if [ ! -f "$DIR/backup" ]; then
            [[ ! "$@" =~ (--quiet) ]] && echo "warning: $TARGET: skipping backup" 1>&2
            EXEC="true" # skip backup
        else
            files=""
            files+=" --files-from=$DIR/backup"
            [ -f "$DIR/exclude" ] && files+=" --exclude-file=$DIR/exclude"
            EXEC="$RESTIC backup $repo $passwd --cleanup-cache $files $@"
        fi
        if [ "${#rotate[@]}" != 0 ]; then
            EXEC+=" && $RESTIC forget $repo $passwd ${rotate[@]} --prune"
            [[ "$@" =~ (--quiet) ]] && EXEC+=" --quiet" # 'forget' should go quiet too
        fi
        EXEC+=" && $RESTIC $repo $passwd check"
        [[ "$@" =~ (--quiet) ]] && EXEC+=" --quiet"
        for i in $(grep -v '^ *#' "$DIR/mirror" 2>/dev/null); do
            rclone_conf="/dev/null"
            rclone_repo="$i"
            # s3:s3.ca-east-006.backblazeb2.com/bucket  --> b2:bucket
            if [[ "$i" =~ ^s3: ]]; then
                rclone_repo="b2:${i/s3:*\//}"
                ep="${i#*:}" && ep="${ep%/*}"
                rclone_conf=$(mktemp --tmpdir "$(basename $0)-rclone.XXXXXX")
cat << EOF > $rclone_conf
[b2]
type = b2
hard_delete = true
env_auth = true
EOF
#endpoint = ${ep}
            [[ "$@" =~ (--dry-run|--pretend) ]] && rm -f "$clone_conf"
            fi
            EXEC+=" && $RCLONE sync $(cat "$DIR/repo") $rclone_repo --config $rclone_conf --fast-list"
            if [[ ! "$@" =~ (--quiet) ]]; then
                EXEC+=" --progress"
            else
                EXEC+=" --quiet"
            fi
            [ "$rclone_conf" != "/dev/null" ] && EXEC+=" && rm -f $rclone_conf"
            EXEC+=" && $RESTIC $passwd --repo "$i" check"
            [[ "$@" =~ (--quiet) ]] && EXEC+=" --quiet"
        done
        ;;
    ncdu) EXEC="${RESTIC} --no-lock $repo $passwd$@ ls latest --ncdu | ${NCDU} -f -";;
    redu) EXEC="${REDU} -j 12 $repo $passwd $@";;
    keys)
        set +ex
            printf "%8s %42s %s\n" $(basename $DIR) $(cat $DIR/repo) $(cat $DIR/passwd)
        for i in $(cat $DIR/env 2>/dev/null); do
            printf "%52s%s\n" "" $i
        done
        for i in $(cat $DIR/mirror 2>/dev/null); do
            printf "%52s%s\n" "" $i
        done
        exit 0
        ;;
    check) EXEC="$RESTIC $repo $passwd $CMD $@";; # TODO check mirrors too!
    *) EXEC="$RESTIC $repo $passwd $CMD $@";;
esac
[ -f "$DIR/hook" ] && EXEC="$DIR/hook before $CMD && trap \"$DIR/hook after $CMD\" EXIT && $EXEC"


if [ -f "$DIR/env" ]; then
    set -a
    source "$DIR/env"
fi
[ -z "$RCLONE_B2_ACCOUNT" ] && RCLONE_B2_ACCOUNT="$AWS_ACCESS_KEY_ID"
[ -z "$RCLONE_B2_KEY" ] && RCLONE_B2_KEY="$AWS_SECRET_ACCESS_KEY"
set +a

[[ "$@" =~ (--dry-run|--pretend) ]] && [[ "x$rclone_conf" != "x" ]] && echo "$rclone_conf" && cat $rclone_conf && rm -f $rclone_conf
[[ "$@" =~ (--dry-run|--pretend) ]] && env | sort && echo "$EXEC" && exit 0

set -e -o pipefail
[[ ! "$@" =~ (--quiet) ]] && set -x
eval "${EXEC}"
